# Generated by Django 4.2.7 on 2024-06-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_zip_code_user_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='house_number',
            new_name='houseNumber',
        ),
    ]
