# Generated by Django 4.2.7 on 2024-06-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_house_number_user_housenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(default='Powstańców Śląskich', max_length=30),
        ),
    ]
