# Generated by Django 4.2.7 on 2024-05-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizuteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fineness',
            field=models.CharField(default=585, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='metal',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
