# Generated by Django 4.2.7 on 2024-02-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizuteria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategoria',
            new_name='Category',
        ),
    ]
