# Generated by Django 4.2.7 on 2024-05-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizuteria', '0002_product_fineness_product_metal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fineness',
            field=models.CharField(default='585', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='metal',
            field=models.CharField(default='Srebro', max_length=15),
        ),
    ]
