# Generated by Django 4.2.7 on 2024-05-23 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bizuteria', '0003_alter_product_fineness_alter_product_metal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='house_number',
            new_name='houseNumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='zipCode',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
