# Generated by Django 4.2.7 on 2024-05-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizuteria', '0004_rename_house_number_order_housenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='subtotal',
        ),
    ]
