# Generated by Django 4.2.7 on 2024-05-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizuteria', '0006_orderproduct_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='bizuteria.OrderProduct', to='bizuteria.product'),
        ),
    ]
