# Generated by Django 4.2.7 on 2024-06-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizuteria', '0010_remove_product_is_available_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fineness',
            field=models.CharField(default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='metal',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
